# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=20)),
                ('upload', models.FileField(upload_to=b'uploads/user_files/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MLobject',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to=b'uploads/ML_object/%Y/%m/%d/')),
            ],
        ),
    ]
